# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b28c2b9ddbb32d2f20d784a9db148adbc9d7ca60e1a962efd3eadbebae3f02b14e122c98d6506a0db8bb17c1157692a2a2fe084da6d37ce7c7fb13210203e9a7

test:
  secret_key_base: df9d8a6c211ab2a267afac7ef2f6d3ecb76574002e9e59f1637149ce1e126ebd234ab110b6c1c841a7cb1598a754f7d83cba6778f2552b9d73aec9fd3e71ad33

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
